---
output: 
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/nature.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 2
lot: true
lof: true
indent: true
header-includes: # include other LaTeX packages here
    \usepackage{booktabs}
    \usepackage{longtable}
    \usepackage{siunitx}
    \usepackage[left]{lineno}
    \usepackage{float}
    \floatplacement{figure}{H}
    \linenumbers
    \pagestyle{plain}
    \raggedbottom 
    \usepackage{indentfirst}
editor_options: 
  chunk_output_type: console
---

<style>
body {
text-align: justify}
</style>

\begin{center}
I will forever be grateful for the love and support that you have selflessly given me
\end{center}

This thesis is a result of the support and effort that has been given to me and is undoubtedly a better piece of work because of this. I can only hope that I am able to support and give as much as has been given to me in the years to come. \par 

Nic, you gave me a chance (but not a projector\rlap{?}!) and I'll forever be grateful for this. Kaitlin, you've taught me a lot, but mostly you've taught me you can be wonderfully lovely AND be mad good at what you do. Laura, the time and support you've given to me has not only made me a better researcher but has actually been really lovely. I'm really glad we all got to work together!! \par

I've been really fortunate to have worked in such a great environment in Bristol, with people who not only want to help but also to see you succeed. David/Vanessa/Caroline/Sam, thanks for being patient and helping me along the way. Emma, thanks so much for getting me out of the lab! \par

Char, who knew Mark Kermode could bring so much love and joy in to someone's life! Nance, you're wonderful(!) but I'm never getting that fleece am I... Steph, you gave me a waffle maker and love, what more could I ask for. Big GG to Jake for giving me friends who don't have real jobs and helped me through lockdown and a PhD. \par

\begin{center}
Mum, if it wasn't for you I wouldn't be here today. I'd be a PE teacher. Thanks for letting me live my life and having my back if shit went wrong.
\end{center}

