---
output: 
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/nature.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 1
lot: true
lof: true
editor_options: 
  chunk_output_type: console
---

This thesis aimed to investigate whether metabolites played an intermediary role in the relationship between adiposity and disease. In Chapter \@ref(introduction), I present an introduction of the literature. In Chapter \@ref(systematic-review), I detail a systematic review and meta-analyses of all Mendelian randomization analyses (MR) which use adiposity measures as an exposure. In Chapter \@ref(visualisation), I present a visualisation tool for summarising large association analyses. In Chapter \@ref(observational), linear regression analyses of the effect of adiposity measures on metabolites in the Avon Longitudinal Study of Parents and Children (ALSPAC) is presented. In Chapter \@ref(MR), MR analyses of the effect of adiposity measures on metabolites using multiple independent datasets, and comparison with results from ALSAPC is presented. In Chapter \@ref(mediation), multivariable MR (MVMR) is used to investigate whether metabolites identified in Chapters 4 and 5 as associated with adiposity are intermediates in the relationship between adiposity and endometrial cancer. In Chapter 7, I discuss the overarching themes and strengths and limitations of the thesis. \par

All of the work in Chapters \@ref(introduction), \@ref(observational), \@ref(MR), and \@ref(mediation) was performed and written by myself. I lead all of the work in Chapter \@ref(systematic-review), which was conducted in collaboration with Charlie Hatcher, Luke A McGuinness, Nancy McBride, Thomas Battram, Si Fang, Wenxin Wan, and Kaitlin H Wade who all contributed to data extraction. I also performed data extraction and, in collaboration with Charlie Hatcher, checked all extracted data for all included studies. I performed all analyses in Chapter \@ref(systematic-review). In Chapter \@ref(visualisation), work was conducted in collaboration with Osama Mahmoud and Luke A McGuinness. I worked with Osama to develop the code that would form the original draft of the visualisation tool, `EpiViz`. Luke McGuinness helped with aspects of the `Shiny` application. The following colleagues provided feedback in the development of `EpiViz`: Caroline Bull, Charlie Hatcher, Kurt Taylor, Nancy Mcbride, Neil Goulding, and Steph Suddell. Work from Chapter \@ref(visualisation) is published open source on [GitHub](https://github.com/mattlee821/EpiViz) and is presented for the first time in Bos et al. (2020)[@Bos2021]. Vanessa Tan and Caroline Bull shared MVMR scripts with me, which I then used for reference in my analyses in Chapter \@ref(mediation). Eleanor Sanderson provided helpful guidance and feedback on the interpretation of MVMR results in Chapter \@ref(mediation). \par

Work in this thesis would not have been possible without the contribution of all the families who took part in ALSPAC, the midwives for their help in recruiting them, and the whole ALSPAC team, which includes interviewers, computer and laboratory technicians, clerical workers, research scientists, volunteers, managers, receptionists and nurses. Thanks to: Adam Butterowtrh (Univeristy of Cambridge) for letting me use summary statistics from INTERVAL, Carolina Borges (University of Bristol) for UK Biobank nuclear magnetic resonance genome-wide association study summary statistics, and Emma Anderson (University of Bristol) for diet trajectory data in ALSPAC. \par