---
output: 
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/nature.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 1
lot: true
lof: true
editor_options: 
  chunk_output_type: console
---

The following outputs are a result of this PhD and their relevance to the content of this thesis are noted. 

**Matthew A Lee**, George McMahon, Ville Karhunen, Kaitlin H Wade, Laura J Corbin, David A Hughes, George Davey Smith, Debbie A Lawlor, Marjo-Riitta Jarvelin, Nicholas J Timpson, Common variation at 16p11.2 is associated with glycosuria in pregnancy: findings from a genome-wide association study in European women, [Human Molecular Genetics, Volume 29, Issue 12, 15 June 2020, Pages 2098–2106](https://doi.org/10.1093/hmg/ddaa054). *Not relevant.*

**Matthew A Lee**, Osama Mahmoud, Luke J McGuinness, David Hughes, Kaitlin H Wade, Laura J Corbin, Nicholas J Timpson, Epiviz: an implementation of Circos plots for epidemiologists, 2020, [github.com/mattlee821/EpiViz](https://github.com/mattlee821/EpiViz). *This `R` package and web application are the focus of Chapter \@ref(visualisation)*

David A Hughes, Kurt Taylor, Nancy McBride, **Matthew A Lee**, Dan Mason, Deborah A Lawlor, Nicholas J Timpson, Laura J Corbin. *metaboprep*:  an `R` package for pre-analysis data description and processing, 2020, [github.com/MRCIEU/metaboprep](https://github.com/MRCIEU/metaboprep). *The `R` package discussed in this pre-print was used in Chapter \@ref(observational) to process metabolomics data.*

Linda M. O’Keeffe, Joshua A. Bell, Kate N. O’Neill, **Matthew A Lee**, Mark Woodward, Sanne Peters, George Davey Smith, Patricia M. Kearney, Sex-specific associations of adiposity with cardiometabolic traits: multi-life-stage cohort study with repeat metabolomics, [medRxiv, 2020](https://doi.org/10.1101/2020.11.30.20240895). *This paper is referenced within the thesis.*

Bos, M.M., Goulding, N.J., **Lee, M.A.** et al. Investigating the relationships between unfavourable habitual sleep and metabolomic traits: evidence from multi-cohort multivariable regression and Mendelian randomization analyses. [BMC Med 19, 69, 2021](https://doi.org/10.1186/s12916-021-01939-0). *This paper is a use case for the `EpiViz` `R` package and is referenced in Chapter \@ref(visualisation).* 

\newpage


