---
output: 
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/nature.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 2
lot: true
lof: true
indent: true
header-includes: # include other LaTeX packages here
    \usepackage{booktabs}
    \usepackage{longtable}
    \usepackage{siunitx}
    \usepackage[left]{lineno}
    \usepackage{float}
    \floatplacement{figure}{H}
    \linenumbers
    \pagestyle{plain}
    \raggedbottom 
    \usepackage{indentfirst}
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
# word count = 
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to') # this will tell the .Rmd file what output you are knitting to (word, pdf, html) so that you cna use if else statements when making tables - html/pdf output tables do not work well in word. For word we need to use the 'flextable' packaged to make tables.
## packages
library(dplyr)
library(kableExtra)
library(flextable)
```

# Discussion {#discussion} 

<style>
body {
text-align: justify}
</style>

## Chapter summary {-}

This thesis has focussed on the role of adiposity in disease development, with a specific focus on the potential intermediary role metabolites play in this relationship. At the end of each of chapters \@ref(systematic-review), \@ref(visualisation). \@ref(observational), \@ref(MR), and \@ref(mediation), the main results, strengths, and limitations of each chapter are described. In this final chapter, a discussion and summary of the strengths, limitations, key findings, and implications of this thesis as a whole, are presented alongside suggestions for future directions that may aid in untangling the mechanisms leading from adiposity to disease. \par 

\newpage

## Overview
Both observational and Mendelian randomization (MR) analyses have provided evidence for an association between adiposity and many health outcomes and diseases. However, with the many limitations of singular adiposity measures (e.g., body mass index (BMI), which is unable to differentiate lean and fat mass[@Flegal2009]), complimentary assessments of body composition are recommended[@WorldHealthOrganisation2008; @Collaboration2009]. This requires a more detailed interrogation of potential effects as each measure provides a different assessment: BMI provides an overall assessment of body composition, body fat percentage (BF) provides an estimate of the specific makeup in terms of fat mass, and waist hip ratio (WHR) provides an estimate of where fat mass is stored. Understanding how adiposity is associated with different outcomes can therefore help to establish a more accurate estimate of the impact of adiposity on health outcomes. \par

The underlying mechanisms for many of the relationships between adiposity and diseases are not well understood. There is some evidence that the physical burden of fat mass is directly related to the development of some diseases. For some diseases, evidence points to changes in the metabolome, proteome, and other omes (e.g., epigenome) as the potential underlying mechanism of disease development[@Cirulli2019; @Castaner2018; @Cominetti2018; @Figarska2020; @FernandesVileigas2021; @DeHeredia2012; @Stryjecki2011; @Fernandez-Real2005]. Many studies have highlighted associations between adiposity and changes to the metabolome[@Cirulli2019; @Moore2014; @OKeeffe2020; @Stevens2020; @Bachlechner2016; @Wulaningsih2019; @Wurtz2014; @SantosFerreira2017; @Lau2020; @Brachem2020; @Frigerio2021; @Neeland2019; @Rangel-Huerta2019; @Boone2019], as well as associations between the metabolome and diseases such as type 2 diabetes[@Ahola-Olli2019], coronary heart disease[@Cavus2019], depression[@Bot2020], hypertension[@Onuh2020], and more[@Gowda2008; @Beger2013; @Verma2015; @Cruickshank-Quinn2018; @SantosFerreira2019; @Hartley2019; @Chi2021; @Bos2021; @Volani2021; @Kovesdy2017]. However, whether metabolites explain the mechanisms of disease development has not been explored in depth. \par

The aim of this thesis was to identify metabolites that sit on the causal pathway between adiposity and disease. A key focus in achieving this was the systematic approach used to investigate adiposity-related effects. I utilised complementary assessment of adiposity, multiple independent sources of data, and complementary methodologies (i.e., observational and MR analyses) to strengthen causal inference. \par 

### Chapter \@ref(systematic-review): adiposity causally impacts numerous risk factors and diseases
The adverse effects of adiposity have been reviewed extensively in the observational literature[@Donato1998; @Safaei2021; @Djalalinia2015; @Luppino2010; @Afshin2017; @Guh2009; @Hruby2016; @Must1999; @Fontaine2001]. However, observational studies have a number of limitations, not least the difficulty in obtaining a causal estimate[@Batty1999; @DaveySmith2014c; @DaveySmith2014; @Timpson2005; @CCGC2011; @Yarmolinsky2018]. These limitations, including confounding and reverse causation, can lead to biased results[@DaveySmith2014; @Timpson2005; @CCGC2011; @Yarmolinsky2018]. MR, a form of instrumental variable analysis, is able to mitigate the effects of many of these limitations due to the fact that genetic variants, used as instrumental variables, are inherited randomly at conception and are temporally prior to any subsequent outcome[@Smith2004]. Although MR has its own set of assumptions and limitations, it has shown promise in untangling causal effects[@Timpson2005; @CCGC2011]. Recently, Riaz et al., (2018)[@Riaz2018] attempted to gain an overview of the causal effects of adiposity on cardiovascular outcomes. They found consistent results with observational estimates, but did not perform quality assessment of the included studies and inappropriately assessed the independence and exclusion restriction assumptions (see Chapter \@ref(introduction) Section \@ref(mendelian-randomization)) as a combined assumption[@Wade2018a]. There has not been a comprehensive investigation of the causal effect of adiposity. \par 

To gain a comprehensive overview of the causal effect of adiposity, i undertook a systematic review and meta-analysis was performed and presented in Chapter \@ref(systematic-review). A total of 173 articles met pre-published criteria for inclusion (see [PROSPERO](https://www.crd.york.ac.uk/prospero/display_record.php?ID=CRD42018096684)), with 34 studies included in meta-analyses of 31 adiposity-outcome pairs. Results from the meta-analyses, which were consistent with published observational studies, identified positive causal effects of adiposity on many cancers, cardiovascular traits, type 2 diabetes, and depression. A narrative synthesis of the studies not included in the meta-analyses revealed a literature that is broadly consistent with observational findings, showing that the causal effects of adiposity are wide reaching. There were however some inconsistencies between the meta-analysis results and the narrative synthesis. For example, endometrial cancer; in meta-analysis, higher BMI was associated with an increased risk of endometrial cancer (OR = 1.57; 95% CI = 1.11 -- 2.22), while in the narrative synthesis, there was inconsistent evidence, with some studies pointing to a decreasing effect and others showing little evidence of an effect in either direction. A similar picture was observed for colorectal cancer. This may be reflective of the differential association with subtypes. \par

Although there was some conflicting evidence in the narrative synthesis for the different exposures, there was much evidence supporting the causal impact of adiposity on many diseases. There is a requirement to understand the mechanisms by which adiposity impacts these outcomes. Given the hypothesis of metabolic perturbations of adiposity, the thesis then focussed on the causal role of adiposity on circulating metabolites, which was then expanded to understand the role of adiposity-related metabolites in endometrial cancer as an exemplar outcome. \par

### Chapter \@ref(visualisation): visualisation of large epidemiological analyses can help to gain global overview and summarise results
Large epidemiological analyses pose a challenge in regards to the exploration, interpretation, display, and communication of results. This is an important consideration in regards to analyses which use correlated data such as metabolites, as looking at a single result may not provide a complete picture. Gaining an overview of results can therefore aid the interpretation of results, and data visualization is a key part of this process[@Tufte1983]. This thesis aimed to investigate the association between adiposity and metabolites using complimentary measures of adiposity. It was therefore important to consider the relationship between metabolites and the relationship between adiposity measures when interpreting results. Previous studies[@May-Wilson2017; @Taylor2019; @Soares2019; @SantosFerreira2019; @Hartley2020; @Borges2017] have used forest plots to interpret and communicate analyses which require comparisons or involve metabolites. However, these studies have been limited to a small number of associations between exposures and outcomes. When dealing with hundreds of variables, forest plots can become cumbersome, requiring many separate plots to be created in order to present all of the analyses. This makes comparison and the ability to gain global overview of large analyses difficult. \par

Circos plots, whereby data are presented in a circular layout, have been used effectively in a number of epidemiological studies using metabolites and performing many hundreds of association analyses[@Kettunen2016; @Shin2014; @Wulaningsih2019; @Bos2021; @Taylor2019]. However, the process of producing Circos plots is cumbersome and, through personal experience[@Taylor2019], has been time consuming and inefficient. To improve the efficiency and reproducibility of creating Circos plots that enable the exploration, interpretation, and display of large, and complex, epidemiological analyses as conducted in this thesis, `EpiViz` was developed. An `R` package and web application, `EpiViz` builds on the `Circlize`[@Gu2014] and `ComplexHeatmap`[@Gu2016] `R` packages to produce Circos plots and was used in Bos et al., (2021) to summarise and visually compare observational and Mendelian randomization analyses of multiple sleep traits with over 100 metabolites. \par

The web application is a simplified version of the `R` package and is intended for researches with no experience in `R`. No coding is required; users simply upload up to three text files, select the parameters for the Circos plot, and then click a button to create the Circos plot. The `R` package provides additional features and is designed for beginner `R` users. More experienced `R` users can easily customise the underlying code to create bespoke Circos plots with, for example, multiple points plotted on a single track (see Figure 2 in Taylor et al., (2019)[@Taylor2019]). The `R` package will be the focus of further development as there is potential for greater utility through the introduction of new features. \par

`EpiViz` considerably improves the speed and efficiency of producing Circos plots and has been used in multiple studies[@Bos2021; @Bell2020; @Taylor2019] since its development. It is important to note that Circos plots, as used in this thesis and other studies[@Bos2021; @Taylor2019; @Bell2020], are not intended to replace other presentation methods. They are best used as a tool to provide an overview of results and should be supplemented with other figures, such as forest plots, to gain a complete picture of association analyses. \par

### Chapter \@ref(observational): adiposity is associated with individual and whole subclasses of metabolites across time points
There is considerable evidence that adiposity is observationally associated with a wide range of metabolites[@Wurtz2014; @Moore2014; @SantosFerreira2017; @Cirulli2019; @Lau2020; @Brachem2020; @Stevens2020; @Wulaningsih2019; @Frigerio2021; @Neeland2019; @Bachlechner2016; @Rangel-Huerta2019]. However, the focus of many studies has been on BMI as a marker for overall adiposity. Additionally, few studies have looked at whether associations persist over time. To gain a greater understanding of the association between different measures of adiposity and metabolites, linear regression analyses using data from the Avon Longitudinal Study of Parents and Children (ALSPAC) were conducted and presented in Chapter \@ref(observational). \par

Data on adiposity measures and up to 230, predominantly lipid-based, nuclear magnetic resonance (NMR) derived metabolites and ratios were available for children (N = 5,656; mean age = 7.56; standard deviation (SD) = 0.36), adolescents (N = 4,489; mean age = 16.06; SD = 1.11), young adults (N = 3,269; mean age = 24.03; SD = 0.85), and adults (N = 6,406; mean age = 49.53; SD = 5.32). Three models were used to estimate the effect of each adiposity measure on each metabolite: model 1 adjusted for age and sex; model 2 = model 1 + mother's/own education, smoking status, alcohol consumption, and diet; model 3 = model 2 + physical activity. Model 1 and 2 were run on individuals with data on all confounders except for physical activity, as there was substantially fewer individuals with physical activity data. \par

The association between all adiposity measures and metabolites was far reaching, with effects seen across all subclasses of metabolites, and results similar to those previously reported[@Wurtz2014]. All three measures of adiposity were associated with a majority of the metabolites across all time points and all models. The exception was for model 3 when investigating the effect of BMI and BF on metabolites in adolescents, which may have been due to reduced power given the smaller sample size available for that model given the number of individuals with missing data on physical activity. There was broad consistency in the directions of effect across models at each time point and adiposity measures at each time point. Generally the effect of adiposity was to increase metabolite concentrations, the exception being high density lipoprotein (HDL) metabolite measures, which decreased with adiposity. Effect sizes tended to be larger increase across all measures of adiposity as age increased (though, this may have been due to an increase in the SD of the exposures with age) . \par

Work in this chapter highlighted the wide reaching effect adiposity has on metabolites and showed that effects likely persist over time. Of particular note was the larger effect sizes and increasing number of associations seen as age increases. Given that many adiposity-associated diseases occur later in life, exposure to an altered metabolic profile over time may be important in disease development. This is especially true as weight loss in overweight and obese individuals is associated with a normalizing of metabolite changes[@Rangel-Huerta2019]. This is noteworthy in regards to comparisons with MR analyses, as exposures instrumented by genetic variants are often thought to approximate a lifetime change in an exposure, and evidence here suggests that adiposity exerts a greater effect as time progresses. Observational analyses, such as those presented in Chapter \@ref(observational), have particular strengths and limitations; thus, the comparison with other study designs with different strengths and limitations provides an opportunity to strengthen causal evidence. Thus, in Chapter \@ref(MR), I performed MR analyses, which have different assumptions and biases than observational analyses, to triangulate and strengthen the evidence questioning the causal impact of adiposity on metabolite levels. \par

### Chapter \@ref(MR): the effect of adiposity on metabolites is consistent across observational and Mendelian randomization analyses 
Parallel two-sample MR analyses in two datasets and subsequent meta-analysis were performed and reported in Chapter \@ref(MR). Data on adiposity measures were available for: BMI in up to 795,624 individuals of European ancestries from GIANT[@Yengo2018], WHR in up to 697,702 individuals of European ancestries from GIANT[@Pulit2019], and BF in up to 89,297 individuals European ancestries from Lu et al.,[@Lu2016]. Metabolite data were available from two independent studies: 123 NMR-derived metabolites and ratios measured in up to 24,925 individuals of European ancestries from Kettunen et al. (2016)[@Kettunen2016], and 230-NMR derived metabolites and ratios measured in up to 40,905 individuals of European ancestries from INTERVAL (unpublished). Both metabolite datasets used the same NMR platform as that used in Chapter \@ref(observational) and were therefore predominantly lipid metabolites. Meta-analysis of 110 metabolites measured in both datasets and, comparison with observational analyses in adults from Chapter \@ref(observational), identified 54 associations between adiposity measures and metabolites that were consistent in their direction of effect across both analyses and which passed various multiple testing thresholds. \par

Results again highlighted the broad effect of adiposity across the metabolome, with evidence for an increasing effect on whole subclasses of metabolites such as very large low density lipoprotein (VLDL; small, very small, medium, large, and very large), as well as for specific metabolites within the aromatic and branched chain amino acids subclasses. Negative effects were, similar to observational analyses, observed for HDL metabolite subclasses (medium, large and very large). The effects of BMI and WHR on metabolites in MR analyses were highly consistent with observational analyses. However, where effects for BF were similar to those of BMI and WHR in observational analyses, effects of BF in MR analyses were generally opposite to BMI and WHR. Evidence for an association between BF and the metabolic profile was weak; effect sizes and confidence intervals (CIs) were much larger than those for BMI and WHR, with the majority of CIs crossing the null. This may have been due to lower statistical power in the BF analyses compared to those with BMI and WHR given the amount of trait variance explained by the genetic variants associated with BF (~0.4%) being much lower than for BMI (6%) and WHR (3%). \par

Given the highly correlated nature of the exposures, and the consistency in observational estimates with metabolites, results for BF appear counter-intuitive. These differences may be due to a true causal negative effect of BF on metabolites, low statistical power, or a result of the difficulty in instrumenting complex traits such as adiposity. BMI and WHR were instrumented using many more single nucleotide polymorphisms (SNPs) than BF (i.e., 941, 316, and 7 SNPs for BMI, WHR, and BF, respectively, in the main analysis), likely decreasing the power in the latter analysis due to the lower variance explained in BF by the genetic variants. This complexity is reflected in the fact that 2 of the 7 SNPs used to instrument BF had previously been associated with 'favourable adiposity'[@Yaghootkar2014; @Yaghootkar2016], that is, they are associated with increased fat mass and a favourable metabolic profile. Removal of these SNPs and re-estimation of the effect of BF on metabolites resulted in a global tightening of CIs and a number of effect estimates changing direction to be more consistent with BMI and WHR. A number of these effects subsequently reached the multiple testing threshold. \par

Work in this chapter, in combination with results from Chapter \@ref(observational), highlighted the effects of adiposity on whole subclasses of metabolites. The use of both MR and observational analyses, which hold different biases, strengthens evidence for an effect of adiposity on 54 metabolites, including amino acids such as tyrosine and phenylalanine, and lipids such as triglycerides in very small, small, medium, large, very large, and extremely large VLDL. Predominantly, the effect of adiposity was to increase these metabolites, with a negative effect of adiposity-associated on HDL metabolites. A number of these associations were consistent with previous observational and MR analyses[@Wurtz2014; @Bull2020], where these adiposity-associated metabolites have been shown to be associated with adiposity-related diseases such as colorectal[@Bull2020] and endometrial cancer[@Kliemann2021], meaning that they could play an intermediary role in these relationships. \par

### Chapter \@ref(mediation): intermediary metabolites may partly contribute to the association between adiposity and diseases identified in Chapter \@ref(systematic-review)

<!--
In Chapter \@ref(systematic-review), three MR analyses were included in a meta-analysis of the effect of BMI on endometrial cancer resulting in an OR of 1.57 (95% CI = 1.11 -- 2.22). In Chapter \@ref(mediation), MR analysis of the effect of BMI on endometrial cancer resulted in an OR of 1.91 (95% CI = 1.75 -- 2.07), similarly strong effects for BF (OR = 2.54; 95% CI = 2.32 -- 2.76) and WHR (OR = 1.26; 95% CI = 0.98 -- 1.53) were also found. In addition, investigation of endometrial cancer subtypes (endometrioid and non-endometrioid) in Chapter \@ref(mediation) showed that the strongest evidence for endometrioid cancer was with BMI and BF; whereas, the strongest evidence for non-endometrioid cancer was with WHR. These results would suggest that body composition is more important in endometrioid development and fat deposition is more important in non-endometrioid cancer development. \par
-->

In Chapter \@ref(mediation), to build on the literature and evidence provided in this thesis, two-sample univariable MR was used to firstly replicate the evidence of the effect of adiposity and adiposity-related metabolites on endometrial cancer, as an exemplar disease, and multivariable MR (MVMR) was then used to assess the potential intermediary role of these metabolites in the relationship between adiposity and endometrial cancer. Endometrial cancer was chosen as an exemplar for this analysis as it met four key requirements: there was strong evidence in Chapter \@ref(systematic-review) for an effect of one or more adiposity measures on endometrial cancer, there was consistent evidence across observational[@WILD2020] and MR[@Gharahkhani2019; @Painter2016; @Yarmolinsky2019] analyses that adiposity is associated with an increased risk of endometrial cancer, there is a large and publicly available genome-wide association study (GWAS) on endometrial cancer, and the extent to which circulating metabolites may play a role in the relationship between adiposity and endometrial cancer had not been published before and thus adds novelty to the literature. \par

Data were available for three endometrial cancer outcomes: endometrioid cancer (cases = 8,758; controls = 108,979), non-endometrioid cancer (cases = 1,230; controls = 108,979), and overall endometrial cancer (cases = 12,906; controls = 108,979), which included cases from endometrioid and non-endometrioid cancer, as well as un-classified endometrial cancer cases. An independent metabolite dataset to those used in Chapters \@ref(observational) and \@ref(MR) was used to replicate the effect of adiposity on metabolites observed in Chapters \@ref(observational) and \@ref(MR) (i.e., providing the best estimate of the effect of adiposity on metabolites), and to estimate the causal effect of metabolites on endometrial cancer risk. There was strong evidence for an effect of BMI, WHR, and BF on an increased risk of overall endometrial, endometrioid, and non-endometrioid cancer. These results were consistent with the effect of BMI on endometrial cancer observed in meta-analysis in Chapter \@ref(systematic-review), as well as with previous observational results reported in the literature by Bhaskaran et al., (2014)[@Bhaskaran2014]. 

A total of 52 metabolites identified in Chapters \@ref(observational) and \@ref(MR) associated with BMI (N = 44), WHR (N = 47), and BF (N = 8) were available for MR analysis using data from UK Biobank. Of these, a consistent direction of effect with results from Chapters \@ref(MR) and \@ref(observational) was found 40 metabolites for BMI, 45 metabolites for WHR, and all 8 metabolites for BF. Seven of these metabolites were only found to be associated with WHR and 5 of these metabolites were uniquely associated with BF. Two metabolites were associated with both BMI and BF and 38 metabolites were associated with both BMI and WHR. Only one metabolite, valine, was associated with all three measures. Of these adiposity-associated metabolites, five were found to be associated with endometrial, endometrioid, or non-endometrioid cancer. Of these five metabolites, valine was the only metabolite found to be negatively associated with the risk of all three outcomes. Phospolipids in very large HDL were positively associated with the risk of endometrial and endometrioid cancer, and negatively associated with risk of non-endometrioid cancer. The remaining three metabolites, triglycerides in small and very small VLDL, and triglycerides in very large HDL were all positively associated with all three outcomes. \par

Only triglycerides in small and very small VLDL had directions of effect with adiposity measures and endometrial cancer which was consistent with a potential intermediary role and were included in MVMR analyses. There was evidence for an intermediate effect of both metabolites on the effect of WHR and BF on non-endometrioid cancer. Although sensitivity analysis did not indicate these effects were due to horizontal pleiotropy, they did suggest that genetic instruments for metabolite were weak (F-statistic < 10); as a result, it is unclear if these metabolites truly mediate the effect of adiposity on endometrial cancer or if this is due to various biases of these analyses. \par

It is difficult to compare these results with previous work given few studies have looked at the intermediate role of metabolites in the relationship between adiposity and endometrial cancer, and those that have, have focussed solely on BMI and have used a clinical measure of triglycerides. These studies have found both an increasing[@Lindemann2009] and decreasing[@Cust2007] effect of triglycerides on endometrial cancer risk after adjustment for BMI. Though there is benefit to looking at metabolite classes (i.e., overall picture of metabolite effects), this does not allow for differentiation in metabolite effects[@Corbin2020], e.g., VLDL may be associated with a decreased risk of endometrial cancer, but triglycerides in small VLDL is associated with an increase in endometrial cancer risk. It is also reasonable to expect that the properties of specific metabolites are exhibited differently in different tissues and cells around the body[@VanderHeiden2009; @DeBerardinis2012; @Zhu2019; @Pavlova2016]. As such, these results suggest that triglycerides are potential intermediates in the relationship between adiposity and endometrial cancer, but this is likely to be specific to non-endometrioid cancer, and specific to the alignment of triglycerides with small and very small VLDL. \par

## Strengths and limitations
Within each chapter, the strengths and limitations of the techniques applied and data used are discussed. However, there are a number of strengths and limitations that are overarching and relevant to the interpretation of results. These overarching themes are discussed herein. \par

### Replication, meta-analysis, and triangulation of evidence
The major strength of this work is the replication of the effect of adiposity on metabolites in observational (Chapter \@ref(observational)) and MR analyses (Chapter \@ref(MR) and \@ref(mediation)) across four independent datasets. In observational analyses (Chapter \@ref(observational)), a majority of metabolites tested were found to be associated with adiposity. In MR analyses (Chapter \@ref(MR)), a majority of the associations identified in observational analyses were replicated across two independent metabolite datasets. Subsequent meta-analysis of MR results, and comparison with observational results, highlighted 54 metabolites to be associated with adiposity. These associations were subsequently replicated in MR analyses using a much larger independent dataset (Chapter \@ref(mediation)). It was also possible to replicate previous MR analyses investigating the effect of BMI on endometrial cancer. \par

Replication of results using different datasets and techniques is a major goal of epidemiological analyses, as different assumptions and biases are tested, and where evidence aligns, triangulation strengthens the evidence for a true effect of an exposure on an outcome[@Lawlor2016]. Analyses here used multiple independent datasets; this included individual level data across four times points from ALSPAC, each analysis of which adjusted for a multitude of covariables, as well as summary level data from three independent metabolite GWAS and up to four GWAS each for BMI, WHR, and BF. These datasets were analysed using linear regression and two-sample MR methods, which included the use of sensitivity analyses to specifically test MR assumptions. As observational and MR analyses have different assumptions, which were tested extensively, there is strong evidence for a causal relationship between adiposity and 54 metabolites. This is further strengthened by the fact that consistent results were obtained across multiple independent metabolite datasets: ALSPAC, Kettunen et al., INTERVAL, and UK Biobank. \par

Replication and triangulation of evidence was focussed primarily on the relationship between adiposity and metabolites. The effect of metabolites on endometrial cancer was not replicated, nor were MVMR analyses which investigated the intermediate effect of metabolites on endometrial cancer risk. The primary reason for a lack of replication was data availability and independence. Although three independent endometrial cancer GWAS were included in the meta-analysis of the effect of BMI on endometrial cancer in Chapter \@ref(systematic-review), two of these were included in the GWAS used in MR analyses in Chapter \@ref(mediation). As the endometrial cancer GWAS used in Chapter \@ref(mediation) is an updated meta-analysis of these studies, these datasets are not independent. An additional consideration is the fact that there are few publicly available cancer GWAS. That being said, there is opportunity for replication using data from the European Prospective Investigation into Cancer and Nutrition (EPIC); however, data are not immediately available for this analysis. \par

### Data, availability, and presentation
Data, its availability, and the independence between datasets were a key component of this thesis. All data used throughout the thesis had previously been collected, this included individual level data from ALSPAC, which was used in Chapter \@ref(observational), and summary level data for adiposity measures, metabolites, and endometrial cancer used in Chapter \@ref(MR) and \@ref(mediation). The majority of the summary level data was publicly available; metabolite data from INTERVAL was provided by collaborators at the University of Cambridge (Adam Butterworth), and metabolite data from UK Biobank was provided by collaborators at the University of Bristol (Carolina Borges). These collaborations enabled the replication and meta-analysis of the effect of adiposity on metabolites. Although multiple testing thresholds were employed, without these additional datasets to perform replication, the chance of false positives is likely to have risen. Data on endometrial cancer was not as readily available. The lack of GWAS data availability is not restricted to endometrial cancer[@Thelwall2020], but it is a common occurrence that, in comparison to other traits, there are few publicly available cancer GWAS, and even fewer GWAS of cancer subtypes. Platforms such as the OpenGWAS[@Elsworth2020; @Hemani2018] and the GWAS Catalog[@Buniello2019] make it easy for researchers to make their data available to the wider research community, and requirements by funders and publishers (including Plan S [coalition-s.org/](https://www.coalition-s.org/)) to make data available should improve the availability of data going forward. \par

In Chapter \@ref(systematic-review), BMI was found to be the most commonly used measure of adiposity when investigating the causal effect of adiposity on outcomes. A main reason for its commonality is that data on BMI is readily collected as a staple of prospective and cohort studies, and there is a history of making summary statistics publicly available[@Speliotes2010; @Locke2015; @Yengo2018; @Pulit2019], which aids further analysis[@Burgess2015c; @Thelwall2020]. BMI however has a number of limitations, not least its inability to differentiate fat and lean mass[@Flegal2009]. Complimentary assessment of adiposity using a combination of body composition measures, is likely beneficial when investigating associations with disease as each has different limitations[@WorldHealthOrganisation2008; @Collaboration2009] (Chapter \@ref(introduction) Section \@ref(adiposity-measures)). Measures of adiposity used in this thesis were chosen in order to encompass the key aspects of adiposity, body composition and fat deposition. BMI was chosen as it is the most commonly used measure and provides an overall estimate of body composition. BF was chosen as, unlike BMI, it is able to capture the fat composition of the body. WHR was chosen as evidence has pointed to an important role of fat deposition in the development of many diseases. Importantly, all three measures have been shown to have different underlying biological pathways[@Loos2018], meaning that when looked at together, a deeper understanding of a relationship with an outcome can be achieved. An additional consideration for choosing WHR and BF, as opposed to other measures that may be more detailed (e.g., visceral adipose tissue), was the availability of data. Much like BMI, there is a history of publicly available data for WHR[@Heid2010; @Shungin2015; @Pulit2019] and an increasing number of publicly available BF datasets[@Lu2016; @Hubel2019]. There are comparatively fewer well powered and publicly available GWAS for more detailed body composition measures such as visceral adipose tissue[@Karlsson2019], making within-exposure replication difficult. \par

An additional challenge with the use of pre-collected and publicly available data is the lack of control over the data available and the methods of collection, which are likely to vary across studies. For instance, in ALSPAC, data on all three measures of adiposity was not available at all time points (for example, data on WHR was not available for adolescents). In addition, data on BF was collected via bioelectrical impedance and dual-energy x-ray absorptiometry (DXA) in the different age groups. Although there was high correlation found between the measures of BF using impedance and DXA data in Chapter \@ref(observational), subtle differences between the measures may lead to differential associations with metabolites and other traits. In order to ensure comparison of adiposity effects were appropriate in Chapter \@ref(observational), adiposity measures were normalised and Z-scores were used in regression models. When using publicly available summary level data however, summary statistics can be interpreted differently depending on the adjustments and transformations applied prior to genome-wide analysis. Summary level data for all adiposity measures had undergone the same inverse rank normal transformation prior to genome-wide analysis, but study-specific adjustments were not the same across the datasets. As such, although estimates reflect a SD unit, that unit will have been adjusted for different covariables. It's worth noting that, whilst comparison between observational and MR results were made, specifically in regards to their directions of effect, the units may not represent the exact same unit in both analyses. It also meant that obtaining clinically informative units was not possible as it is not appropriate to back-calculate and estimate an SD unit change without the underlying distributions of the data, which was not available. The format of publicly available data used in two-sample MR is a common limitation and it is a strength of one-sample MR that the researcher can control the processing prior to analysis. \par

Pre-analysis processing of data is particularly important for metabolomics data[@Hughes2021], where researchers characterize and prepare data prior to analyses. This may include identifying poor quality samples and metabolites and/or a broad array of additional, and researcher specific, processes, such as transformations. In Chapter \@ref(observational), the `metaboprep` `R` package - the development of which I was involved in - was used in an effort to perform transparent and informed processing of ALSPAC metabolite data. In using `metaboprep`, there are a number of threshold settings that can be altered, though in thisinstance default settings were used. The default settings however are arbitrarily assigned or have been set based on previous published work, for example, sample missingness is set to 20% by default based on work by Lotta et al. (2021)[@Lotta2021]. A more stringent threshold (e.g., 5%) may have impacted on the number of samples excluded. Of particular note from this pre-analysis processing step performed in Chapter \@ref(observational) is the fact that, although almost all metabolites were shared across age groups, the number of independent metabolites identified by `metaboprep` differed across age groups. As metabolite data used in MR analyses were publicly available or provided by collaborators, it was not possible to use the same pre-analysis processing strategy. Comparison of effect sizes was not possible across observational and MR analyses (only comparison of the direction of effect) as different transformations and adjustments had been made to the GWAS data used in MR analyses. This also meant it was not possible to meta-analyse the MR analyses performed in Chapter \@ref(MR) using effect estimates (i.e., Fisher's method meta-analysis p-values was instead used). Future work should look to use a standardised method for pre-analysis processing, such as `metaboprep`, while a centralised approach to analysis of metabolomics data across cohorts, such as that being employed by the Consortium of Metabolomics Studies[@Temprosa2021], will allow for more efficient comparisons and meta-analyses of studies. \par

A strength of the metabolomics data used in these analyses was however the fact that all of the metabolomics data came from the same NMR platform, which has been described previously[@Soininen2009; @Inouye2010; @Kettunen2012; @Soininen2015] and in Chapter \@ref(observational). As the same platform was used it was possible to compare directions of effect across methods and datasets for almost all metabolites. Of important note however is the fact that this NMR platform is predominantly lipid based. Although many lipids are larger than the traditionally defined size of a metabolite[@Wishart2007] they are detected reliably by the platform[@Soininen2009]. The platform also provides many derived measures, such as ratios and number of bonds. Although this NMR platform measures a broad array of metabolites, including amino acids and glycoproteins, it is limited and is therefore not reflective of the metabolome as a whole. Rather, it reflects the lipidome and a small number of non-lipid metabolites. \par

Given the high-dimensionality of measures used in this thesis and the need to compare across multiple exposures and analyses, a particular challenge was how to effectively summarise and interpret the large number of association analyses performed. Throughout this thesis, forest plots and Circos plots were used to summarise, interpret, and present results from the over 2,000 analyses conducted. A key aspect of this was `EpiViz`, presented in Chapter \@ref(visualisation), which was developed in order to improve the efficiency and reproducibility of producing Circos plots and to make them more accessible to a wider audience. `EpiViz` has been successfully used in published work[@Bos2021; @Bell2020; @Taylor2019] and as the availability and interest in molecular data grows, it is likely that more researchers will look to similar visualisation tools to interpret and communicate results. As it stands, `EpiViz` successfully creates Circos plots for summarising and communicating large association analyses. Future development should focus first on converting the current code style to the [`tidy` style](https://tidyverse.tidyverse.org/articles/manifesto.html) to improve readability and consistency. This will also improve the use of the package in the future enabling more contributors. Outside of this, future development will be through requests from the community to meet their needs. \par

### Methodology, instrumentation, and assumptions {#discussion-assumptions}
A key aspect of the work in this thesis was the use of a systematic review and meta-analyses (Chapter \@ref(systematic-review)), observational (Chapter \@ref(observational)), and two-sample MR (Chapter \@ref(MR)) analyses to inform the investigation of the effect of adiposity-related metabolites on adiposity-related diseases. As stated above, this strategy of triangulation strengthens evidence for observed effects as each method has its own limitations and sources of bias. For example, observational epidemiology is limited by confounding and reverse causation. Prospective studies, such as ALSPAC used in Chapter \@ref(observational), are able to provide some temporal separation between the measurement of an exposure and outcome, and thus mitigate the potential effects of reverse causation. However, as data on adiposity measures and metabolites were collected at the same time, reverse causation remains a limitation. It was however possible to account for the potential effects of confounding in Chapter \@ref(observational) by adjusting linear models for covariables such as: age, sex, mother's or own education, smoking status, alcohol consumption, diet, and physical activity. Although many covariables were included across the models, it is likely these analyses will not have fully accounted for confounding, either due to measurement error or unmeasured confounding. For example, adults were asked 'do you take part in physical activity (e.g. running, swimming, dancing, golf, tennis, squash, jogging, bowls)?', with possible answers of 'no', 'occasionally (less than monthly)' and 'frequently (once a month or more)'. Broad categories such as these are unlikely to capture the full impact of physical activity given that 'frequently' will encompass individuals who exercise once a month as well as every day. \par

MR analysis, which is more resilient to limitations of observational analyses such as confounding and reverse causation[@DaveySmith2003], has its own set of assumptions and limitations, such as genetic confounding and horizontal pleiotropy (Chapter \@ref(introduction) Section \@ref(mendelian-randomization)). MR has three main assumptions and a number of additional assumptions, all discussed in detail in Chapter \@ref(introduction) Section \@ref(mendelian-randomization), that must be satisfied in order to obtain reliable results. The first of these assumptions, that instruments are robustly associated with the exposure, can be satisfied by using instruments obtained from well-powered GWAS, which are independent of one another, and which meet a robust genome-wide significance threshold (e.g., p-value < 5 x 10^-8^). All instruments used in MR analyses in this thesis were obtained from well powered GWAS which used strict linkage disequilibrium (LD) r^2^ thresholds and a genome-wide significance threshold of p-value < 5 x 10^-8^. In additional analyses performed in Chapter \@ref(MR), a more conservative LD r^2^ threshold was used where the effect of these instruments on metabolites was consistent with the less conservative LD r^2^ threshold used in the main analyses. \par

This instrument selection strategy, of selecting the largest most recent GWAS with a strong independence and genome-wide significance threshold, was the most commonly used approach in studies included in the systematic review in Chapter \@ref(systematic-review). However, it is not clear whether this strategy is the most appropriate for all traits. In this regard, consideration needs to be given to the potential that SNPs associated with the measures of adiposity may also be associated directly with metabolites or metabolic pathways. The exclusion restriction assumption states that the instrument must act on the outcome only via the exposure, where violation of this assumption can bias results. Horizontal pleiotropy such as this is difficult to test for directly. Sensitivity analyses, using models sensitive to the effects of horizontal pleiotropy (MR-Egger, weighted median, and weight mode), were consistent with the main analysis in Chapter \@ref(MR) and \@ref(mediation) suggesting weak evidence of horizontal pleiotropy. The Steiger directionality test can also be used to test whether the "true" causal direction is the one under investigation, i.e., the effect of adiposity measures on metabolites. Results from Steiger directionality tests in Chapter \@ref(MR) suggested that the effects of horizontal pleiotropy were most likely apparent when using instruments with large SNP lists such as the 941-SNP instrument for BMI. However, given that the directions of effect for these large SNP lists were highly consistent with the smaller SNP lists instrumenting the same exposures (which showed a majority of "true" causal directions), the interpretation of the directions of effect are likely the same across the SNP lists. This does not fully address the potential for direct associations between SNPs associated with the exposure and the outcome however, and future work should look at exploring the genetic correlation between adiposity measures and metabolites. \par

For analyses in Chapter \@ref(mediation) investigating the effect of metabolites on endometrial cancer, instruments were identified using the same strategy described above and applying the stringent LD r^2^ threshold used in additional analyses in Chapter \@ref(MR). However, given the strong inter-correlated nature of metabolites and the fact many metabolites are products of one another, this instrumentation strategy may not be appropriate. For instance, it is possible that SNPs associated with metabolites do not conform to the third instrumental variable (IV) assumption - that the SNPs do not affect the outcome except through the exposure. In this sense, the effect of a metabolite on an outcome could be through a highly correlated second metabolite. For the two metabolites identified in Chapter \@ref(mediation), with evidence of an intermediary role on the effect of adiposity on endometrial cancer, a total of 56 and 50 SNPs were associated at a genome-wide significance threshold of p-value <Z5 x 10^-8^ and an LD r^2^ threshold of 0.001. Of these SNPs, 16 were shared across the two metabolites. It is likely both metabolites also share SNPs with many other metabolites, given that just over half of the 934 identified SNPs for the 53 metabolites investigated in Chapter \@ref(mediation) were associated with just one metabolite and the average number of SNPs associated with a metabolite was 49. This issue of SNP specificity in regards to metabolites has been looked at previously[@Guida2021]. Findings suggested that SNP specificity was low (i.e., many shared SNPs) and, more often than not, the variance explained for any metabolite instrument was higher for an alternative metabolite. The non-specificity of instruments has two potential outcomes - horizontal and vertical pleiotropy. However, distinguishing one from the other, with specific regard to metabolite instruments, is challenging[@Swerdlow2016]. In analyses here, a single instrumentation approach was used for metabolites and, given the likely shared genetic architecture across the tested metabolites, the presence of both horizontal and vertical pleiotropy can not be ruled out. Future work should focus particularly on the use of colocalisation methods[@Foley2021] to identify shared genetic signals across related traits. \par

When investigating the effect of adiposity measures on metabolites in Chapter \@ref(MR), the exposure and outcome GWAS were sex-combined. In addition, adiposity instruments used in Chapter \@ref(mediation) were obtained from sex-combined GWAS. A key limitation of this work is therefore the use of non-sex-specific instruments for measures of adiposity. A major driver of endometrial cancer, specifically endometrioid cancer, is oestrogen[@WILD2020], which, as a sex hormone, is important in endometrial cell growth. Oestrogen is also involved in the distribution and accumulation of adipose tissue[@Wells2007]. Importantly, adipose tissue is a key source of oestrogen synthesis, particularly post-menopause[@Simpson2003]. There is sexual dimorphism in the accumulation and distribution of adipose tissue highlighted in genetic studies, which have found sex-specific SNPs associated with adiposity[@Locke2015; @Shungin2015; @Pulit2019; @Yengo2018; @Hubel2019]. There is also evidence of sex differences in the associations between adiposity and metabolites[@OKeeffe2020]. There is however utility in the use of sex-combined instruments as they provide an overarching view of the effect of adiposity that is independent of the sexual dimorphism associated with adiposity. There is some evidence to suggest that there is little difference in the use of sex-combined compared to sex-specific summary statistics in sex-specific analyses[@Martin2021; @Tyrrell2019], though this is possibly dependent upon the question under investigation (i.e., effects may differ depending upon the exposure or outcome)[@Ruth2020]. That being said, replication using sex-specific instruments will only add to the evidence found in this thesis. \par

A key assumption of two-sample MR is the independence of the two samples. Overlap between the exposure and outcome datasets in a two-sample MR can bias estimates towards the confounded observational estimate in a manner proportional to the size of the overlap in the presence of weak instruments[@Burgess2016]. Given that many publicly available summary statistics are meta-analyses which include many different cohorts, there is always the possibility of overlap when using GWAS with hundreds of thousands of participants. However, for analyses performed in Chapter \@ref(MR), there was no overlap between the cohorts included in the adiposity GWAS with cohorts used in the metabolite GWAS. GWAS of BMI and WHR used in the main analyses of Chapter \@ref(MR) included individuals from UK Biobank and additional analyses used GWAS which did not include UK Biobank. Results from both analyses were highly consistent. In Chapter \@ref(mediation), metabolite and endometrial cancer data were available from GWAS which included individuals from UK Biobank. In order to minimise the amount of overlap given that metabolite and endometrial cancer data used included individuals from UK Biobank, BMI and WHR instruments were obtained from GWAS used in the additional analyses in Chapter \@ref(MR) which did not include individuals from UK Biobank. \par

For binary outcomes, the bias due to overlap is specific to the overlap between individuals in the exposure GWAS and those who are cases in the outcome GWAS. As 5% of the endometrial cancer cases were UK Biobank participants, the relative bias for the effect of metabolites on endometrial cancer was at most 0.5%. Specifically, this bias is applicable to the effect of metabolites on endometrial cancer, and the effect of metabolites adjusted for adiposity measures on endometrial cancer. The bias is not applicable to the effect of adiposity measures adjusted for metabolites on endometrial cancer, as the instruments for these analyses were obtained from the adiposity GWAS which did not include individuals from UK Biobank. Recent work has shown that the use of strong instruments can mitigate the bias induced by sample overlap[@Sadreev2021] and, although there was evidence for weak instruments for some metabolites, including when used in MVMR analysis, the majority of those instruments used in univariable MR were strong (F-statistic > 10). \par

Issues of sample overlap were not limited to the MR analyses performed in Chapter \@ref(MR) and \@ref(mediation), it was also an issue in Chapter \@ref(systematic-review). Of the over 2,000 MR analyses identified in the systematic review, a total of 71 MR analyses were included in 31 meta-analyses. The majority of these 31 meta-analyses included only two MR analyses. This meant that interpretation of heterogeneity statistics[@VonHippel2015; @Jackson2017] and the use of funnel plots to assess publication bias, was difficult. One of the main reasons for these small numbers was the fact that studies were excluded from the meta-analyses if there was: (i) sample overlap between outcome data across MR analyses, (ii) and/or if there was sample overlap between exposure and outcome data across MR analyses. As many of the largest and most recent MR analyses used samples from GWAS that were used in prior MR analyses, these larger analyses were preferred for inclusion as they encompassed estimates from previous analyses. However, given that many MR analyses use data from large GWAS consortia, and given that reporting quality was not high for a majority of studies, it is possible that there is overlap in the meta-analysed MR analyses that was not identified during screening. It is possible to estimate the overlap between samples using LD score regression (LDSR)[@Yengo2018a], but this can only be achieved with summary data which was not readily available when extracting data for studies included in the systematic review. With the drive for GWAS to use ever larger sample sizes and for consortia to join forces to perform meta-analyses of meta-analyses, it may become more challenging to identify truly independent samples in MR analyses. This will be a particular concern in regards to MR meta-analyses where there is more opportunity for sample overlap given the need to have independence between outcome data across studies and exposure and outcome data across studies. \par

### General assumptions of Mendelian randomization analyses
Generally, MR analyses use unrelated individuals and assume that genotypes share no common causes with the outcome. Where this assumption is not satisfied, estimates of the association between the SNP and exposure can be biased. This can be a result of population structure, selection bias, assortative mating, dynastic effects, and canalisation[@DaveySmith2003; @Davies2019a]. Canalisation, whereby what would otherwise be developmentally deleterious genetic effects are nullified by compensatory mechanisms, results in effect estimates attenuating to the null[@Smith2004]. Though being aware of the underlying biology can inform analyses, accounting for canalisation is difficult as it is currently difficult to test for its presence[@Dixon2016]. Confounding by population structure on the other hand would bias estimates towards the observational confounded estimate. Generally this is accounted for in GWAS using principle components or linear mixed models[@Price2006a; @Loh2015]. However, there is evidence of residual effects of population structure in large and small GWAS of apparently homogeneous samples using both methods[@Haworth2019; @Lawson2020; @Sarmanova2020; @Sanderson2021; @Sohail2019]. In Chapter \@ref(MR), additional analyses aimed to obtain consistent effects using multiple instrumentation practices and GWAS to obtain instruments for BMI, WHR, and BF. Consistent effects using GWAS of different populations suggests any effect of population structure is limited and did not drastically alter results. That being said, there was considerable difference in directions of effect when using the two BF GWAS. It is possible that these conflicting results are due to the difficulty in instrumenting BF as opposed to population structure, given that removing two 'favourable adiposity' SNPs from one SNP list resulted in a number of effect estimates changing direction. \par

Selection bias, whereby study participation is non-random, can induce an association between genotypes associated with study participation and other traits correlated with study participation. For example, if a study aims to recruit individuals with endometrial cancer, but individuals with a high BMI are more willing to participate in the study than those with a lower BMI, an association between high BMI and endometrial cancer would have been induced as a result of study participation. As many of the cohorts contributing to the GWAS used in this thesis were prospective, individuals would not have been selected based on disease status. However, there is some evidence that individuals with certain cancers, e.g., prostate cancer, are diagnosed at a later stage as a result of a higher BMI[@Hu2014]. This could mean that individuals with adiposity during early cancer stages are less likely to be diagnosed, or that adiposity is associated with a faster progression to advanced prostate cancer. \par

An additional consideration is that individuals do not mate at random. Assortative mating is a form of sexual selection in which individuals are more alike (i.e., similar phenotype or genotype) than one would expect at random. There is evidence to suggest that individuals with similar heights and weights are more likely to mate than at random[@Silventoinen2003]. This can be because of a direct relationship, that is, partners select because of a phenotype, or an indirect relationship, where partners select because of background (e.g., ancestry or culture) that is also associated with the phenotype of interest. Additionally, there is potential for partner phenotypes to converge. These effects can be either single (e.g., adiposity) or multi-trait (e.g., adiposity and level of education). Bias in MR results is only induced by multi-trait assortative mating, as it induces associations between the two exposures through their associated instruments, that is, SNPs associated with adiposity will become associated with level of education and vice versa. It is not possible to evaluate or test for the effects of assortative mating using summary level data[@Davies2019a]. \par 

Dynastic effects are a form of confounding as a result of generational traits which influence offspring phenotypes[@Sanderson2019; @Brumpton2019]. Inherited parental alleles can influence the offspring phenotype through a direct path. In addition, the inherited and non-inherited parental alleles influence the parental phenotype which in turn influences offspring phenotype through an environmental path. In this regard, the second MR assumption would be violated as there would be an association between offspring phenotype and parental genotype that was not directly through the transmission of alleles but, rather, there would be a common cause of the offspring genotype and outcome. For example, the effect of adiposity on endometrial cancer might be biased by a dynastic effect in which a confounding path links genetic instruments for adiposity to endometrial cancer via the correlation between offspring and parental adiposity genotype and the possibility that parental adiposity, specifically maternal adiposity, influences foetal growth and development in utero, which influences future offspring endometrial cancer risk. As with all of these limitations, dynastic effects are not easily tested when using summary level data. Nor is it possible to evaluate their effects outside of family based studies[@Sanderson2019; @Brumpton2019].  \par

<!--
That being said, it may be the case that traits like metabolites are less susceptible to bias due to dynastic effects compared to traits like education and BMI as individuals are blind to their effect.
-->

The issues of dynastic effects, assortative mating, and population structure (familial biases) can be mitigated through the use of family based studies[@Davies2019a; @Brumpton2019]. This is because alleles, inherited from parents, will be independent of the familial biases if conditioned on the parents' genotypes. Importantly, an association between non-inherited alleles and traits in the offspring can only be through parental phenotypes or via the aforementioned familial biases. However, conditioning on the parents' genotypes does not account for the effect of the parental phenotype. It is possible to estimate the effect of the parental phenotype using MVMR, but it is not possible to assign a specific bias to any estimated effect. Although family, specifically trio (i.e., two parents and an offspring) based studies can account for familial biases, the scarcity of genetic and phenotypic data on parents and offspring makes these analyses difficult[@Davies2019a; @Brumpton2019]. ALSPAC is one such study with trio data, however this data is limited in size and, as offspring are comparatively young, investigations of disease such as cancer are not possible. Prospective studies such as the Norwegian Mother, Father and Child Cohort Study (MoBa) and The Nord-Trndelag Health Study (HUNT) include a larger number of trios, but are also limited in their use to investigate disease outcomes given that data is needed on trios and outcomes. Twin-based and sibship studies, which are larger in number, can also be used, though not to the same level, to test for familial biases[@Davies2019a]. Though analyses may include small sample sizes, if evidence is consistent across analyses when used in conjunction with traditional MR analyses using unrelated individuals then this will strengthen evidence[@Lawlor2016] and suggest the effects of familial bias are limited. \par

### Additional considerations

This thesis hypothesised that the direction of effect was true for the effect of adiposity on metabolites and endometrial cancer, and for metabolites on endometrial cancer. It did not however investigate the reverse of this, that the direction of effect was from metabolites to adiposity, and from endometrial cancer to metabolites and adiposity. Although there was evidence for the former, this does not rule out an effect of the latter. This is especially true given: (i) adipose tissue is a complex signalling organ, (ii) cancerous cells are complex signallers that re-wire metabolic processes, (iii) and metabolites are multi-functional with roles in energy, signalling, transportation, and structural components. In observational and MR analyses, there is considerable evidence that the relationship between adiposity and endometrial cancer is in the tested direction. As such, the reverse was not investigated here. In regards to the effect of metabolites on adiposity, the Steiger directionality tests performed in Chapter \@ref(MR), as discussed in Section \@ref(discussion-assumptions), suggested the majority of tests of the effect of adiposity on metabolites were 'true' causal directions. Further investigation of the effects of those analyses which did not reflect a 'true' causal direction is warranted, as there may be evidence that those metabolites are either highly pleiotropic with adiposity or influence adiposity. For the effect of metabolites on endometrial cancer and its reverse, the picture is complex. There is evidence that concentrations of metabolites are altered as a result of cancer[@Pavlova2016]. However, it is not clear how these changes manifest. For example, it is difficult to disentangle whethere they are a result of cancer cells responding to a nutrient poor environment (nutrients may be available but they may not benefit the cancer cell) and their subsequent metabolic reprogramming, they are a result of metabolic reprogramming of cancer cells and the subsequent survival of those cancerous cells that are able to utilise the available nutrients, or if they are a result of both selective pressures at once. These questions cannot be asked in an epidemiological context. Instead, results here can inform wet lab studies by providing potential candidates that can be used to investigate these questions. \par

Finally, a major component of this work was the comparison of observational and MR estimates to obtain evidence for an effect of adiposity measures on metabolites. A key limitation of this comparison is the fact that MR studies may represent different underlying processes to that of observational studies. Exposures instrumented by genetic variants reflect a lifetime change in an exposure, while for observational studies, the exposures are determined by genetic and non-genetic factors at that point in time. The fact that consistent results were observed across observational (Chapter \@ref(observational)) and MR anayses (Chapter \@ref(MR)) using independent datasets, and that these results were replicated in a further MR analysis using an additional independent dataset (Chapter \@ref(mediation)) provides robust evidence for an effect of adiposity on metabolites even if the underlying processes are different. \par

## Future work
Work in this thesis identified two metabolites that may play intermediary roles in the development of endometrial cancer as a consequence of adiposity. The primary focus of this work was the use of complementary assessment of adiposity, NMR-based metabolites, and use of complementary methodologies (observational and MR analyses). The aim and objectives of this thesis (Chapter \@ref(introduction) Section \@ref(aims)) were designed to better understand the underlying mechanisms of adiposity-associated disease development. Although this aim has largely been achieved, there remain some unanswered questions and some new questions stemming from the presented results. \par 

A key question that remains is the replication of the effect of metabolites on endometrial cancer. The limited availability of independent endometrial cancer datasets meant this was not immediately possible. However, there is an opportunity in the future within the EPIC collaboration to investigate these associations. Data will be available on individuals who have undergone bariatric surgery, including endometrial tissue, that could enable the tracking of metabolite changes through the surgery process. This could include investigating the effect of weight reduction, which would act as a complementary analysis to analyses performed in this thesis, investigating whether weight reduction leads to a reduction in metabolites identified in this thesis as up-regulated by adiposity and associated with endometrial cancer. Changes in these metabolites, within endometrial tissue, as a result of weight loss would strengthen evidence found in this thesis. \par

Endometrial cancer was used as an exemplar and a natural follow on would be to investigate the intermediary role of metabolites with other outcomes identified in Chapter \@ref(systematic-review) that were associated with adiposity. Of particular interest would be investigations of breast and prostate cancer, both of which exhibit hormone dependence and independence, as the intermediary role of metabolites here appeared to be specific to hormone independent (non-endometrioid cancer) cancer. Follow up analyses, especially of those relating to cancer, could be to examine the effect of increased triglycerides in small and very small VLDL on cell lines. There is evidence that dosing endometrial cancer cells with specific metabolites increases proliferation rates[@Gibson2018]. A candidate metabolite could be that of myristic acid (a component of the triglyceride trimyristin[@NationalCenterforBiotechnologyInformation2021]), which is associated with endometrial cancer development[@Lindemann2009]. Follow up experiments such as these, which use epidemiological and causal methods to identify candidates for molecular investigation, have shown promise in identifying molecular mechanisms of disease development[@Nounu2021]. \par

Follow up wet lab studies would benefit greatly from a more comprehensive assessment of the metabolome. As discussed earlier, metabolites here were limited to an NMR platform that was predominantly composed of lipids. Many of these metabolites are large transporters of smaller metabolites. Expanding the metabolites available for analysis to include these smaller metabolites such as those identified in un-targeted mass spectrometry analyses, where there is available genetic data[@Shin2014], will enable a broader assessment of the effects of adiposity. \par

The key take away from this thesis in regards to the effect of adiposity-related metabolites on endometrial cancer is that there is some evidence for an intermediate effect, that is not driven by horizontal pleiotropy but may be a result of weak instrument bias. As such, future work should look to improve on the instrumentation strategy used here. Closely related metabolites within the same subclass as those tested here could be combined and collapsed to create a new instrument that represents the broad effect of these metabolites[@Bull2020]. Alternatively, as both metabolites tested here share similar attributes and have similar genetic associations, a composite measure could be used to instrument their combined effect[@Sulc2021]. \par

## Conclusion {-}
Within this thesis, I have demonstrated that: (i) there is a wide literature providing strong evidence for a causal effect of adiposity on many outcomes, (ii) adiposity has a likely causal effect on a large number of predominantly lipid metabolites, (iii) and a number of these metabolites may partly explain the relationship between adiposity and endometrial cancer risk. I have highlighted the complex issues that surround these findings, notably the difficulty instrumenting adiposity and metabolites, and have used a broad array of techniques to strengthen the evidence for an effect of adiposity on metabolites and of adiposity-related metabolites on endometrial cancer risk. In this discussion chapter, I have summarised the findings of this thesis and the overarching strengths and limitations. I have made suggestions for future work that could extend and strengthen results here, and have provided a basis from which hypotheses involving large molecular datasets can be investigated in the future. \par

\newpage

