---
output: 
    thesisdown::thesis_pdf: default
bibliography: bib/thesis.bib
csl: csl/nature.csl
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
toc-depth: 2
lot: true
lof: true
editor_options: 
  chunk_output_type: console
---

# Conclusion {-}
Within this thesis, I have demonstrated: (i) a literature with strong evidence for a causal effect of adiposity on many outcomes, (ii) that adiposity is observationally and causally associated with a large number of predominantly lipid metabolites, (iii) and that a number of these metabolites may partly explain the relationship between adiposity and endometrial cancer risk. I have highlighted the complex issues that surround these findings, notably the difficulty instrumenting adiposity and metabolites, and have used a broad array of techniques to strengthen the evidence for an effect of adiposity on metabolites and of adiposity-related metabolites on endometrial cancer risk. In this discussion chapter I have summarised the findings of this thesis and the overarching strengths and limitations. I have made suggestions for future work that could extend and strengthen results here, and have provided a basis from which hypothesise involving large molecular datasets can be investigated in the future. \par

\newpage