---
author: 'Matthew A Lee'
date: 'April 2021'
title: 'A pipeline for Mendelian randomization studies using large metabolomics data as intermediates'
university: 'University of Bristol'
faculty: 'Health Sciences'
school: 'Bristol Medical School'
group: 'MRC Integrative Epidemiology Unit, Population Health Sciences'
degree: 'PhD Population Health Sciences'
logo: data/index/figures/UoBcrest.pdf
wordcount: '9999999'
bibliography: bib/library.bib
csl: csl/nature.csl
knit: "bookdown::render_book"
site: "bookdown::bookdown_site"
toc-depth: 1
lot: true
lof: true
space_betwee_paragraphs: true
fig_caption: true
always_allow_html: yes
link-citations: true
header-includes: # include other LaTeX packages here
    \usepackage{booktabs}
    \usepackage{longtable}
    \usepackage{siunitx}
    \usepackage[left]{lineno}
    \linenumbers
    \pagestyle{plain}
    \raggedbottom 
output: 
    thesisdown::thesis_pdf: default
#    thesisdown::thesis_gitbook: default
#    thesisdown::thesis_word: default
#    thesisdown::thesis_epub: default
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-acknowledgements.Rmd"), collapse = '\n  ')`
declaration: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-declaration.Rmd"), collapse = '\n  ')`
abbreviations: |
  `r if(knitr:::is_latex_output()) paste(readLines("00-abbreviations.Rmd"), collapse = '\n  ')`
---

```{r include_packages, include = FALSE}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
source("data/index/packages.R")
```

`r if(!knitr:::is_latex_output()) '# Preface {-}'`

`r if(!knitr:::is_latex_output()) '## Abstract {-}'`

```{r abstract, child = "00-abstract.Rmd", eval = !knitr:::is_latex_output()}
```

`r if(!knitr:::is_latex_output()) '## Acknowledgements {-}'`

```{r acknowledgements, child = "00-acknowledgements.Rmd", eval = !knitr:::is_latex_output()}
```
